[package]
name = "enc28j60"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
embedded-hal.workspace = true
simple-network = { workspace = true, optional = true }

[features]
default = []
simple-network = ["dep:simple-network"]
